name: CI/CD Docker vers Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      # ðŸ”‘ AUTHENTIFICATION AZURE (OBLIGATOIRE)
      - name: Connexion Ã  Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Connexion Ã  Azure Container Registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login \
          ${{ secrets.ACR_LOGIN_SERVER }} \
          -u ${{ secrets.ACR_USERNAME }} \
          --password-stdin

      - name: Build de lâ€™image Docker
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/nodeapp:latest .

      - name: Push de lâ€™image vers ACR
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/nodeapp:latest

      - name: DÃ©ploiement sur Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.ACR_LOGIN_SERVER }}/nodeapp:latest
